os: linux

language: go

go:
    - 1.13.x
services:
    - docker

script:   
    # Test the code
    - go test -v ./...
    # Build the code 
    - CGO_ENABLED=0 GOARCH=amd64 go build -o demo
    - echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin    
    - docker build -f Dockerfile -t $REGISTRY_USER/demo:latest ./
    - GIT_SHA="$(git rev-parse --short HEAD)"
    - docker tag $REGISTRY_USER/demo:latest $REGISTRY_USER/demo:$GIT_SHA
    - docker push $REGISTRY_USER/demo:latest
    - docker push $REGISTRY_USER/demo:$GIT_SHA
